import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    chart_config:{
      interval:"15",
      timezone:"Asia/Bangkok",
      theme:"dark",
      style:"1",
      locale:"th_TH",
      toolbar_bg:"#f1f3f6",
      hide_side_toolbar:true,
      enable_publishing:false,
      withdateranges:false,
      allow_symbol_change:false,
      show_popup_button:false,
      popup_width:"1000",
      popup_height:"650",
    },
    current_page: "BTC",
    config_web:{},
    wss_data_ticker: {},
    current_wss_path: "thb_btc",
    current_asset:{},
    show_navbar:false,
    renderComponent: true,
    componentKey:0,
    showPage:false,
    crypto_data: {
      BTC: {},
      ETH: {},
      XRP: {},
      LTC: {},
      BCH: {},
      USDT: {},
      BNB: {},
      XLM: {},
      ADA: {},
      BSV: {},
      WAN: {},
      OMG: {},
      ZIL: {},
      SNT: {},
      CVC: {},
      LINK: {},
      IOST: {},
      ZRX: {},
      KNC: {},
      RDN: {},
      ABT: {},
      MANA: {},
      SIX: {},
      JFIN: {},
      EVX: {},
      POW: {},
      DOGE: {},
      DAI: {},
      USDC: {},
      BAT: {},
      MKR: {},
      BAND: {},
      COMP: {},
      KSM: {},
      DOT: {},
      NEAR: {},
      SCRT: {},
      GLM: {},
      YFI: {},
      UNI: {},
      AAVE: {},
      ALPHA: {},
    },
    titleBar:"Home",
    token:"",
    username:"",
    email:"",
    group:0,
  },
  mutations: {
  },
  actions: {
  },
  modules: {}
})