import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    chart_config:{
      interval:"15",
      timezone:"Asia/Bangkok",
      theme:"dark",
      style:"1",
      locale:"th_TH",
      toolbar_bg:"#f1f3f6",
      hide_side_toolbar:true,
      enable_publishing:false,
      withdateranges:false,
      allow_symbol_change:false,
      show_popup_button:false,
      popup_width:"1000",
      popup_height:"650",
    },
    current_page: "BTC",
    config_web:{},
    wss_data_ticker: {},
    current_wss_path: "thb_btc",
    current_asset:{},
    show_navbar:false,
    renderComponent: true,
    componentKey:0,
    showPage:false,
    crypto_data: {
      BTC: 0,
      ETH: 0,
      XRP: 0,
      LTC: 0,
      BCH: 0,
      USDT: 0,
      BNB: 0,
      XLM: 0,
      ADA: 0,
      BSV: 0,
      WAN: 0,
      OMG: 0,
      ZIL: 0,
      SNT: 0,
      CVC: 0,
      LINK: 0,
      IOST: 0,
      ZRX: 0,
      KNC: 0,
      RDN: 0,
      ABT: 0,
      MANA: 0,
      SIX: 0,
      JFIN: 0,
      EVX: 0,
      POW: 0,
      DOGE: 0,
      DAI: 0,
      USDC: 0,
      BAT: 0,
      MKR: 0,
      BAND: 0,
      COMP: 0,
      KSM: 0,
      DOT: 0,
      NEAR: 0,
      SCRT: 0,
      GLM: 0,
      YFI: 0,
      UNI: 0,
      AAVE: 0,
      ALPHA: 0,
      ENJ: 0,
      CRV: 0,
    },
    titleBar:"Home",
    token:"",
    username:"",
    email:"",
    group:0,
  },
  mutations: {
  },
  actions: {
  },
  modules: {}
})